### PR TITLE
Indentation and formatting

### PR DESCRIPTION
**Pull request by cynical-incendiary**

### CODE REVIEW

**Comment by RhinosF1** [comment]
Hey @awesomelyidiot,

Thanks for your help. Only thing blocking the merge is my WikiBreak Enforcer on my WikiPedia Account.

**Review by RhinosF1 — APPROVED** [review]
Much appreciated!!

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Please review again due to #22 which was pushed first

**Comment by cynical-incendiary** [comment]
Switched to "switch" statement instead of using a bunch of else-ifs. I'd _like_ to see it being AJAX-fied.

**Comment by RhinosF1** [comment]
I'll need to test this @awesomelyidiot first but looks fine.

Are you on Wikipedia?

**Comment by cynical-incendiary** [comment]
Yep, once in a while.

**Comment by RhinosF1** [comment]
@awesomelyidiot, What's your username?

Probably won't test tonight as I've got a few things to do IRL and WikiPedia Has just started having issues.

**Comment by cynical-incendiary** [comment]
[User:RainFall](https://en.wikipedia.org/wiki/User:RainFall)
Okay, sure thing. Wikipedia has started having issues?

**Comment by RhinosF1** [comment]
There were a few issues accessing it earlier, I'll try and get it pushed tommorow as I'm UK so we're too late now for me to test and push everything. It might be best to push as part of test for Task 2 of RF1 Bot as that does updating everything but js page for the script

**Comment by RhinosF1** [comment]
You can add it to your skin.js/common.js pages on wiki.

**Comment by cynical-incendiary** [comment]
And [it works](https://test.wikipedia.org/w/index.php?title=User:RainFall/Status&action=history). ;)

**Review by RhinosF1 — APPROVED** [review]

**Comment by RhinosF1** [comment]
Just need to deploy now, Haven't got time now but I'll try tonight or tommorow

**Comment by RhinosF1** [comment]
Doing...

**Comment by RhinosF1** [comment]
Done

**Pull request merged**
